news/urls.py
from django.urls import path
from .views import homenews, articoloDetailView, listaArticoli, queryBase, giornalisti_list_api, giornalisti_api, articoli_list_api, articoli_api

app_name = 'news'
urlpatterns = [
    path('articoli/<int:pk>', articoloDetailView, name="articolo_detail"),
    path('', homenews, name="homeview"),
    path('lista_articoli/<int:pk>', listaArticoli, name="lista_articoli_giornalista"),
    path('lista_articoli/', listaArticoli, name="lista_articoli"),
    path('query_base/', queryBase, name="query_base"),
    
    path('giornalisti_list_api/', giornalisti_list_api, name="giornalisti_list_api"),
    path('giornalisti_api/<int:pk>', giornalisti_api, name="giornalisti_api"),
    path('articoli_list_api/', articoli_list_api, name="articoli_list_api"),
    path('articoli_api/<int:pk>', articoli_api, name="articoli_api"),
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage,welcome,lista,chi_siamo,variabili,index

app_name="prima_app"
urlpatterns=[
    path('hompage', homepage, name='homepage'),
    path('welcome', welcome, name='welcome'),
    path('lista', lista, name='lista'),
    path('chi_siamo', chi_siamo, name='chi_siamo'),
    path('variabili', variabili, name='variabili'),
    path('', index, name='index')
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app',include("prima_app.urls", namespace="prima_app")),
    path('seconda_app',include("seconda_app.urls", namespace="seconda_app")),
    path('prova_pratica_1',include("prova_pratica_1.urls", namespace="prova_pratica_1")),
    path('news/',include("news.urls", namespace="news")),
    path('voti/',include("voti.urls", namespace="voti")),
    path('products/',include("products.urls", namespace="products")),
    path('',index,name="index")
]   

seconda_app/urls.py
from django.urls import path
from seconda_app.views import es_if, if_else_elif,es_for,index_seconda

app_name="seconda_app"
urlpatterns=[
    path('es_if', es_if, name='es_if'),
    path('if_else_elif', if_else_elif, name='if_else_elif'),
    path('es_for', es_for, name='es_for'),
    path('', index_seconda, name='index_seconda')
]

voti/urls.py
from django.urls import path
from voti.views import view_a,view_b,view_c,view_d

app_name="voti"
urlpatterns=[
    path('view_a/', view_a, name='view_a'),
    path('view_b/', view_b, name='view_b'),
    path('view_c/', view_c, name='view_c'),
    path('view_d/', view_d, name='view_d'),
]

primo_progetto/views.py
from django.shortcuts import render

def index(request):
    return render(request, "index_root.html")

primo_progetto/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} Primo progetto {% endblock title %}</title>
     <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index'%}">Primo progetto</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Prima app
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">homepage</a>
              <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">welcome</a>
              <a class="dropdown-item" href="{% url 'prima_app:lista'%}">lista</a>
              <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">chi_siamo</a>
              <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">variabili</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Seconda app
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">es_if</a>
              <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">if_else_elif</a>
              <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">es_for</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              prova pratica 1
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'prova_pratica_1:'%}">vindex</a>
              <a class="dropdown-item" href="{% url 'prova_pratica_1:view_a'%}">view_a</a>
              <a class="dropdown-item" href="{% url 'prova_pratica_1:view_b'%}">view_b</a>
              <a class="dropdown-item" href="{% url 'prova_pratica_1:view_c'%}">view_c</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Prova Pratica 2
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'voti:view_a'%}">Lista materie (view_a)</a>
              <a class="dropdown-item" href="{% url 'voti:view_b'%}">Voti studenti (view_b)</a>
              <a class="dropdown-item" href="{% url 'voti:view_c'%}">Media studenti (view_c)</a>
              <a class="dropdown-item" href="{% url 'voti:view_d'%}">Max min voti (view_d)</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container my-4">
      <!--imserire contenuti della pagina-->
      {%block content%}
      {%endblock content%}
      <!--inserire codice javascript-->
      {%block script%}
      {%endblock script%}

    </div>
  </body>
</html>

primo_progetto/templates/index_root.html
{% extends "base.html"%}
    
{%block title%} {{block.super}} | Index_root {%endblock title%}

{%block content%}
    <h1>PRIMO PROGETTO - ROOT MENU'</h1>
    <ol>
        <li><a href="/admin">pannello admin</a></li>
        <li><a href="{% url 'prima_app:index'%}">index prima app</a></li>
        <li><a href="{% url 'seconda_app:index_seconda'%}">index seconda app</a></li>
        <li><a>.....</a></li>
    </ol>
    <!-- <a href="/admin">Pannello admin</a>, {% url 'prima_app:index'%} -->
    
{%endblock content%}